# https://school.programmers.co.kr/learn/courses/30/lessons/151141

SELECT H.HISTORY_ID,
CASE 
    WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN CONVERT(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) * (1-D.DISCOUNT_RATE/100),SIGNED)
    ELSE (C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1))
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
    AND(
        (DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 7 AND 29 AND D.DURATION_TYPE='7일 이상')
        OR 
        (DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 30 AND 89 AND D.DURATION_TYPE='30일 이상')
        OR 
        (DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 AND D.DURATION_TYPE='90일 이상')
        OR DATEDIFF(H.END_DATE, H.START_DATE)<7
    )
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC 