/* https://school.programmers.co.kr/learn/courses/30/lessons/131532 */

SELECT DATE_FORMAT(O.SALES_DATE,'%Y') AS YEAR,
MONTH(O.SALES_DATE) AS MONTH,
GENDER, COUNT(DISTINCT(I.USER_ID)) AS USERS
FROM ONLINE_SALE O JOIN USER_INFO I
ON O.USER_ID=I.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER ASC
