# https://school.programmers.co.kr/learn/courses/30/lessons/133027

SELECT H.FLAVOR FROM FIRST_HALF H JOIN 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.TOTAL_ORDER+J.TOTAL_ORDER DESC
LIMIT 3