-- https://school.programmers.co.kr/learn/courses/30/lessons/293260

SELECT COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH
ORDER BY MONTH ASC

-- https://school.programmers.co.kr/learn/courses/30/lessons/293257

SELECT COUNT(ID) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO F JOIN FISH_NAME_INFO N
WHERE F.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC