-- https://school.programmers.co.kr/learn/courses/30/lessons/273711

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY="RARE")
AND T.PARENT_ITEM_ID IS NOT NULL
ORDER BY I.ITEM_ID DESC

-- https://school.programmers.co.kr/learn/courses/30/lessons/273710

SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL