-- https://school.programmers.co.kr/learn/courses/30/lessons/131124
WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ),
    REVIEW_MAX AS (
        SELECT MAX(REVIEW_COUNT) AS MAX FROM REVIEW_COUNT
    )
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM (MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID)
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM REVIEW_COUNT C JOIN REVIEW_MAX ON REVIEW_COUNT=MAX)
ORDER BY REVIEW_DATE, REVIEW_TEXT