-- https://school.programmers.co.kr/learn/courses/30/lessons/299305

SELECT E1.ID, COUNT(E2.ID) AS CHILD_COUNT
FROM ECOLI_DATA E1 LEFT JOIN ECOLI_DATA E2
ON E1.ID=E2.PARENT_ID
GROUP BY E1.ID
ORDER BY E1.ID

-- https://school.programmers.co.kr/learn/courses/30/lessons/298519

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH,10))>=33
ORDER BY FISH_TYPE ASC

-- https://school.programmers.co.kr/learn/courses/30/lessons/293261

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY I.ID ASC