-- https://school.programmers.co.kr/learn/courses/30/lessons/276035

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D JOIN SKILLCODES S
WHERE S.CATEGORY = "Front End" AND D.SKILL_CODE & S.CODE = S.CODE
ORDER BY ID ASC