-- https://school.programmers.co.kr/learn/courses/30/lessons/299307

SELECT ID, CASE
    WHEN SIZE_OF_COLONY <= 100 THEN "LOW"
    WHEN SIZE_OF_COLONY <= 1000 THEN "MEDIUM"
    ELSE "HIGH" END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC

-- https://school.programmers.co.kr/learn/courses/30/lessons/301649

SELECT ID,CASE
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.25 THEN "CRITICAL"
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.50 THEN "HIGH"
WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) <= 0.75 THEN "MEDIUM"
ELSE "LOW"
END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC