-- https://school.programmers.co.kr/learn/courses/30/lessons/284531

SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),"km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC

-- https://school.programmers.co.kr/learn/courses/30/lessons/284530

SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1),2) AS PM10, ROUND(AVG(PM_VAL2),2) AS `PM2.5`
FROM AIR_POLLUTION
WHERE LOCATION2="수원"
GROUP BY YEAR
ORDER BY YEAR