-- https://school.programmers.co.kr/learn/courses/30/lessons/131116

WITH M_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자","국","김치","식용유")
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN M_PRICE M
ON (F.CATEGORY, F.PRICE)=(M.CATEGORY,M.PRICE)
ORDER BY F.PRICE DESC