-- https://school.programmers.co.kr/learn/courses/30/lessons/164670
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ', STREET_ADDRESS1,' ', STREET_ADDRESS2) AS 전체주소, INSERT(INSERT(TLNO,4,'','-'),9,'','-') AS 전화번호
FROM USED_GOODS_USER U
WHERE USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(BOARD_ID)>=3)
ORDER BY USER_ID DESC
