-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) AS PURCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH