-- https://school.programmers.co.kr/learn/courses/30/lessons/301647

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A JOIN ECOLI_DATA B
ON A.PARENT_ID=B.ID
WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY A.ID


-- https://school.programmers.co.kr/learn/courses/30/lessons/299310

WITH M AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT M.YEAR, M.SIZE-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E JOIN M
ON YEAR(E.DIFFERENTIATION_DATE)=M.YEAR
ORDER BY M.YEAR, YEAR_DEV